# Generated by Django 2.0 on 2018-01-02 20:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_auto_20180102_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=None, size=None),
        ),
    ]
